config/routes.rb
FotosWeb::Application.routes.draw do

  resources :fotos, :only => [:index, :create, :destroy]

end

app/models/foto.rb
class Foto < ActiveRecord::Base
 	
	include Rails.application.routes.url_helpers
	
	image_accessor :imagem
	
	def imagem_multipla=(value)
		self.imagem = value.first
	end

   #one convenient method to pass jq_upload the necessary information
	def to_jq_upload
		{
		 "name" => read_attribute(:imagem_name),
		 "size" => imagem.size,
		 "url" => foto_path(:id => id),
		 "thumbnail_url" => imagem.thumb('80x80#').url,
		 "delete_url" => foto_path(:id => id),
		 "delete_type" => "DELETE" 
		}
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController

  def index
    @foto = Foto.all

    respond_to do |format|
      format.html
      format.json  { render :json => @foto.collect { |p| p.to_jq_upload }.to_json }
    end

  end

  def create

 
    @foto = Foto.new(params[:foto])

    if @foto.save
     render :json => [ @foto.to_jq_upload ].to_json
    else 
     render :json => [ @foto.to_jq_upload.merge({ :error => "custom_failure" }) ].to_json
    end

  end

  def destroy
    @foto = Foto.find(params[:id])
    @foto.destroy
    render :json => true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/index.html.erb
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/base/jquery-ui.css" id="theme">
<%= stylesheet_link_tag 'jquery.fileupload-ui' %>

<div id="fileupload">
    <%= form_for Foto.new, :html => { :multipart => true } do |f| %>
        <div class="fileupload-buttonbar">
            <label class="fileinput-button">
                <span>Add files...</span>
                <%= f.file_field :imagem_multipla, :multiple=>true %>
            </label>
            <button type="submit" class="start">Start upload</button>
            <button type="reset" class="cancel">Cancel upload</button>
            <button type="button" class="delete">Delete files</button>
        </div>
    <% end %>
    <div class="fileupload-content">
        <table class="files"></table>
        <div class="fileupload-progressbar"></div>
    </div>
</div>


<script id="template-upload" type="text/x-jquery-tmpl">
    <tr class="template-upload{{if error}} ui-state-error{{/if}}">
        <td class="preview"></td>
        <td class="name">${name}</td>
        <td class="size">${sizef}</td>
        {{if error}}
            <td class="error" colspan="2">Error:
                {{if error === 'custom_failure'}}Custom Error Message
                {{else}}${error}
                {{/if}}
            </td>
        {{else}}
            <td class="progress"><div></div></td>
            <td class="start"><button>Start</button></td>
        {{/if}}
        <td class="cancel"><button>Cancel</button></td>
    </tr>
</script>

<script id="template-download" type="text/x-jquery-tmpl">
    <tr class="template-download{{if error}} ui-state-error{{/if}}">
        {{if error}}
            <td></td>
            <td class="name">${name}</td>
            <td class="size">${sizef}</td>
            <td class="error" colspan="2">Error:
                {{if error === 1}}File exceeds upload_max_filesize (php.ini directive)
                {{else}}${error}
                {{/if}}
            </td>
        {{else}}
            <td class="preview">
                {{if thumbnail_url}}
                    <a href="${url}"><img src="${thumbnail_url}"></a>
                {{/if}}
            </td>
            <td class="name">
                <a href="${url}"{{if thumbnail_url}} target="_blank"{{/if}}>${name}</a>
            </td>
            <td class="size">${sizef}</td>
            <td colspan="2"></td>
        {{/if}}
        <td class="delete">
            <button data-type="${delete_type}" data-url="${delete_url}">Delete</button>
        </td>
    </tr>
</script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
<%= javascript_include_tag 'jquery.iframe-transport' %>
<%= javascript_include_tag 'jquery.fileupload' %>
<%= javascript_include_tag 'jquery.fileupload-ui' %>
<script type="text/javascript" charset="utf-8">
    $(function () {
        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload();


        // 
        // Load existing files:
        $.getJSON($('#fileupload form').prop('action'), function (files) {
            var fu = $('#fileupload').data('fileupload');
            fu._adjustMaxNumberOfFiles(-files.length);
            fu._renderDownload(files)
                .appendTo($('#fileupload .files'))
                .fadeIn(function () {
                    // Fix for IE7 and lower:
                    $(this).show();
                });
        });

        // Open download dialogs via iframes,
        // to prevent aborting current uploads:
        $('#fileupload .files a:not([target^=_blank])').live('click', function (e) {
            e.preventDefault();
            $('<iframe style="display:none;"></iframe>')
                .prop('src', this.href)
                .appendTo('body');
        });

    });
</script>

app/views/fotos/new.html.erb
<h1>Nova foto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', fotos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FotosWeb</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :headers %>
</head>
<body>

<%= yield %>

</body>
</html>